### ISSUE TITLE
Unable to Upload Composer Dependency "NotifyLK" to Repository

### ISSUE THREAD

**Issue by iamhelitha** [notifylk/notify-php#1]
I ran into a problem while attempting to upload my project, which has the NotifyLK SMS API requirement loaded using Composer, to my GitHub repository. NotifyLK, while being located in the vendor subdirectory in my project directory, is not being submitted to the repository. As a result, the SMS functionality that relies on NotifyLK is not accessible in the repository. Could you please guide how to get around this issue? Thank you.

**Comment by maduonline** [comment]
Hi @iamhelitha, thank you for posting your matter. but to assist with this situation we need further information. Could you please WhatsApp us via the number displayed in our website www.notify.lk?
